### ISSUE TITLE
different username/password

### ISSUE THREAD

**Issue by gionag** [xvzf/zyxel-gpon-sfp#6] opened 2022-03-10 23:29 UTC
Hello,
i have the same zyxel gpon.. but the admin/1234 combo don't work as login.
Can someone explain how they were discovered in the first place so i can replicate the same tecnique on my module ?

thanks

**Comment by gionag** [comment] 2022-03-12 11:16
useful trick, maybe for others.
mine was shipped with admin account enabled but with different password than "1234".
i have found a trick to reset that to 1234.

first, login to 10.10.1.1 as guest/guest (mine was enabled)
then, in the same session, enter this :

http://10.10.1.1/cgi/set_admin?rand=0.7041383755617387&type=2&username=admin&password=31rmzl323334m&level=0
it should respond with "1".

After that, re-login with admin/1234 and "save settings" to store that change.

**Comment by xvzf** [comment] 2022-03-18 07:12
Feel free to create a PR and update the readme @gionag

**Comment by k0xak** [comment] 2022-07-25 12:21
I have two modules purchased as used from Italy (Wind3 ISP probably)

First module works with 10.10.1.1 and admin/admin + admin/1234

Second module is listeing on 10.10.1.1 and initial login admin/admin work as well but than am unable to login with admin/1234. Root is identified as not existing user and guest/guest is not working as well.

Any tip for how to get in?

**Comment by LucaDev** [comment] 2022-08-18 20:52
> useful trick, maybe for others. mine was shipped with admin account enabled but with different password than "1234". i have found a trick to reset that to 1234.
> 
> first, login to 10.10.1.1 as guest/guest (mine was enabled) then, in the same session, enter this :
> 
> http://10.10.1.1/cgi/set_admin?rand=0.7041383755617387&type=2&username=admin&password=31rmzl323334m&level=0 it should respond with "1".
> 
> (rand param can be whatever you want from 0 to 1 (1 excluded) as per JS Math.random() output)
> 
> After that, re-login with admin/1234 and "save settings" to store that change.

Thank you so much for that information! I was able to reset the admin password and it works like a charm!

**Comment by gionag** [comment] 2022-08-18 21:37
> > useful trick, maybe for others. mine was shipped with admin account enabled but with different password than "1234". i have found a trick to reset that to 1234.
> > first, login to 10.10.1.1 as guest/guest (mine was enabled) then, in the same session, enter this :
> > http://10.10.1.1/cgi/set_admin?rand=0.7041383755617387&type=2&username=admin&password=31rmzl323334m&level=0 it should respond with "1".
> > (rand param can be whatever you want from 0 to 1 (1 excluded) as per JS Math.random() output)
> > After that, re-login with admin/1234 and "save settings" to store that change.
> 
> Thank you so much for that information! I was able to reset the admin password and it works like a charm!

Glad it helped. In the end i was unable to use the module to properly connect to "TIM" (IT) GPON network... so i switched for another module alltogether

**Comment by slemke76** [comment] 2022-10-21 15:14
Hello,

the admin Password for newer builds is "9dsxsqcq6t" - knowing this stops the need for restting the password every time after config reset / loss.

"show version" of my firmware:
Build Time:                2020-12-23 18:07:36
GIT Info:                  TW2362H-CDEL_lantiq98035/customize/TW2362H-CDEL_lantiq98035_general_20150131:ff6e8bf8


How to reproduce:
-------------------
Reset the module to defaults
Open Webinterface
This will write the actual config: http://10.10.1.1/cgi/set_save?rand=0.4798344808717123
Set the admin Password to '1234': http://10.10.1.1/cgi/set_admin?rand=0.7041383755617387&type=2&username=admin&password=31rmzl323334m&level=0
Login with SSH to the Module - ssh Login is "admin/admin" the CLI Login (as previous set) "admin/1234"
Open the shell with "linuxshell"
Display the previous saved default password: grep -ie "admin Password" /var/config/mib.conf

When I find some time I will make a PR.

Regards,
Sebastian

**Comment by wagman77** [comment] 2023-10-18 20:04
Hi,
I purchased this module from Telekom in summer 2023 and I was also facing the password issue.
Furthermore I was unable to redirect the web interface via ssh command.
I hope that one of the given passwords will work so that I have access to the device.

**Comment by nullinger** [comment] 2024-01-09 23:45
Strange. I purchased the module some days ago and could still use the old credentials.

**Comment by 3DJupp** [comment] 2024-03-08 16:52
Hey, i have "**V1.00(ABVJ.1)b1e**" but i can't access ssh. The connection will be refused all the time.
I did this:
> ssh -o HostKeyAlgorithms=+ssh-rsa admin@10.10.1.1 -v

**Comment by jaseg** [comment] 2024-03-13 21:19
@3DJupp Which specific error do you get? Could you paste a log here? If it actually says "connection refused", then that's not a problem with username/password, but instead means that SSH can't even open a TCP connection to the module (perhaps because of a bad routing table or a firewall interfering?).

**Comment by slemke76** [comment] 2024-06-11 09:05
I havbe just created a pull request which also describes how to (re-)set the password permanently.

**Comment by slemke76** [comment] 2024-06-12 07:24
The pull request has been merged, I guess the ticket can be closed?

**Closed** 2024-06-18 08:39 UTC

**Comment by justjanne** [comment] 2024-11-28 17:46
> @3DJupp Which specific error do you get? Could you paste a log here? If it actually says "connection refused", then that's not a problem with username/password, but instead means that SSH can't even open a TCP connection to the module (perhaps because of a bad routing table or a firewall interfering?).

Newer versions of the module ship with the dropbear shell removed entirely.
